from .bert_loader import BERT_Loader
from .unsup_loader import UNSUP_Loader

max_seq_lengths = {     'stackoverflow': 45,
                        'clinc': 30,
                        'banking': 55,
                        'snips': 35,
                        'avocado': 138,
                        'send_new': 147,
                        'send_new_refined': 147,
                        'send_new_refined_request': 147,
                        'send_new_refined_request_provide': 147,
                        'feedback_meeting_problem': 326,
                        'feedback_meeting_problem_even': 326,
                        'clustered': 79063
                    }
                    
backbone_loader_map = {
                            'bert': BERT_Loader,
                            'bert_CDAC': BERT_Loader,
                            'bert_DTC': BERT_Loader,
                            'bert_KCL_simi': BERT_Loader,
                            'bert_KCL': BERT_Loader,
                            'bert_MCL': BERT_Loader,
                            'bert_MTP':BERT_Loader,
                            'bert_MTP_Pretrain':BERT_Loader,
                            'bert_USNID': BERT_Loader,
                            'bert_USNID_Unsup': BERT_Loader,
                            'glove': UNSUP_Loader,
                            'sae': UNSUP_Loader,
                            'bert_SCCL' : BERT_Loader,
                            'bert_GCD': BERT_Loader,
                            'bert_CC': BERT_Loader,
                            'bert_DeepAligned': BERT_Loader
                      }

benchmark_labels = {
    'clinc': 
            ['accept_reservations', 'account_blocked', 'alarm', 'application_status', 'apr', 
             'are_you_a_bot', 'balance', 'bill_balance', 'bill_due', 'book_flight', 
             'book_hotel', 'calculator', 'calendar', 'calendar_update', 'calories', 
             'cancel', 'cancel_reservation', 'car_rental', 'card_declined', 'carry_on', 
             'change_accent', 'change_ai_name', 'change_language', 'change_speed', 'change_user_name',
             'change_volume', 'confirm_reservation', 'cook_time', 'credit_limit', 'credit_limit_change', 
             'credit_score', 'current_location', 'damaged_card', 'date', 'definition', 
             'direct_deposit', 'directions', 'distance', 'do_you_have_pets', 'exchange_rate',
             'expiration_date', 'find_phone', 'flight_status', 'flip_coin', 'food_last', 
             'freeze_account', 'fun_fact', 'gas', 'gas_type', 'goodbye', 
             'greeting', 'how_busy', 'how_old_are_you', 'improve_credit_score', 'income', 
             'ingredient_substitution', 'ingredients_list', 'insurance', 'insurance_change', 'interest_rate',
             'international_fees', 'international_visa', 'jump_start', 'last_maintenance', 'lost_luggage', 'make_call', 
             'maybe', 'meal_suggestion', 'meaning_of_life', 'measurement_conversion', 'meeting_schedule', 
             'min_payment', 'mpg', 'new_card', 'next_holiday', 'next_song',
             'no', 'nutrition_info', 'oil_change_how', 'oil_change_when', 'order',
             'order_checks', 'order_status', 'pay_bill', 'payday', 'pin_change', 
             'play_music', 'plug_type', 'pto_balance', 'pto_request', 'pto_request_status',
             'pto_used', 'recipe', 'redeem_rewards', 'reminder', 'reminder_update', 
             'repeat', 'replacement_card_duration', 'report_fraud', 'report_lost_card', 'reset_settings', 
             'restaurant_reservation', 'restaurant_reviews', 'restaurant_suggestion', 'rewards_balance', 'roll_dice', 
             'rollover_401k', 'routing', 'schedule_maintenance', 'schedule_meeting', 'share_location', 
             'shopping_list', 'shopping_list_update', 'smart_home', 'spelling', 'spending_history', 
             'sync_device', 'taxes', 'tell_joke', 'text', 'thank_you', 
             'time', 'timer', 'timezone', 'tire_change', 'tire_pressure', 
             'todo_list', 'todo_list_update', 'traffic', "transactions", "transfer", 
             "translate", "travel_alert", "travel_notification", "travel_suggestion", "uber", 
             "update_playlist", "user_name", "vaccines", "w2", "weather",
             "what_are_your_hobbies", "what_can_i_ask_you", "what_is_your_name", "what_song", "where_are_you_from", 
             "whisper_mode", "who_do_you_work_for", "who_made_you", "yes"],

    'banking':  
                [
                    "Refund_not_showing_up", "activate_my_card", "age_limit", "apple_pay_or_google_pay", "atm_support", 
                    "automatic_top_up", "balance_not_updated_after_bank_transfer", "balance_not_updated_after_cheque_or_cash_deposit", "beneficiary_not_allowed", "cancel_transfer", 
                    "card_about_to_expire", "card_acceptance", "card_arrival", "card_delivery_estimate", "card_linking", 
                    "card_not_working", "card_payment_fee_charged", "card_payment_not_recognised", "card_payment_wrong_exchange_rate", "card_swallowed", 
                    "cash_withdrawal_charge", "cash_withdrawal_not_recognised", "change_pin", "compromised_card", "contactless_not_working", 
                    "country_support", "declined_card_payment", "declined_cash_withdrawal", "declined_transfer", "direct_debit_payment_not_recognised", 
                    "disposable_card_limits", "edit_personal_details", "exchange_charge", "exchange_rate", "exchange_via_app", 
                    "extra_charge_on_statement", "failed_transfer", "fiat_currency_support", "get_disposable_virtual_card", "get_physical_card", 
                    "getting_spare_card", "getting_virtual_card", "lost_or_stolen_card", "lost_or_stolen_phone", "order_physical_card", 
                    "passcode_forgotten", "pending_card_payment", "pending_cash_withdrawal", "pending_top_up", "pending_transfer", 
                    "pin_blocked", "receiving_money", "request_refund", "reverted_card_payment?", "supported_cards_and_currencies", 
                    "terminate_account", "top_up_by_bank_transfer_charge", "top_up_by_card_charge", "top_up_by_cash_or_cheque", "top_up_failed", 
                    "top_up_limits", "top_up_reverted", "topping_up_by_card", "transaction_charged_twice", "transfer_fee_charged", 
                    "transfer_into_account", "transfer_not_received_by_recipient", "transfer_timing", "unable_to_verify_identity", "verify_my_identity", 
                    "verify_source_of_funds", "verify_top_up", "virtual_card_not_working", "visa_or_mastercard", "why_verify_identity", 
                    "wrong_amount_of_cash_received", "wrong_exchange_rate_for_cash_withdrawal"
                ], 
    'stackoverflow':
                        [
                            "ajax", "apache", "bash", "cocoa", "drupal", 
                            "excel", "haskell", "hibernate", "linq", "magento", 
                            "matlab", "oracle", "osx", "qt", "scala", 
                            "sharepoint", "spring", "svn", "visual-studio", "wordpress"
                        ],
    'snips':
                [
                    "AddToPlaylist", "BookRestaurant", "GetWeather", "PlayMusic", "RateBook",
                    "SearchCreativeWork", "SearchScreeningEvent"
                ],
    'avocado':
                [
                    "send_feedback", "send_meeting_request", "send_files",
                    "send_invoice", "send_presentation", "send_test_results",
                    "send_resume", "send_helpdesk_request", "resend_virus",
                    "send_bug_report", "send_contact_info", "send_contract",
                    "send_updates", "send_excel_spreadsheet", "resend_it",
                    "send_invite_evite", "offer_help", "send_pictures",
                    "send_status_report", "send_project_plans", "send_information",
                    "send_feature_list", "send_logs", "send_gifts", "send_translation",
                    "send_document_another_version", "send_list", "send_signed_copy"
                ],
    'send_new':
                [
                    'send_review', 'send_presentation', 'send_fax',
                    'send_update_changes', 'send_pictures', 'send_meeting_request',
                    'send_resume'
                ],
    'send_new_refined':
                [
                    'send_review', 'send_presentation', 'send_fax',
                    'send_update_changes', 'send_pictures', 'send_meeting_request',
                    'send_resume'
                ],
    'send_new_refined_request':
                [
                    'send_review_request', 'send_presentation_request',
                    'send_fax_request', 'send_update_changes_request',
                    'send_pictures_request', 'send_meeting_request_ambiguous',
                    'send_meeting_request_request', 'send_resume_request'
                ],
    'send_new_refined_request_provide':
                [
                    'send_review_provide', 'send_review_request',
                    'send_presentation_provide', 'send_presentation_request',
                    'send_fax_provide', 'send_fax_request',
                    'send_update_changes_provide', 'send_update_changes_request',
                    'send_pictures_request', 'send_pictures_provide',
                    'send_meeting_request_provide', 'send_meeting_request_request',
                    'send_resume_request', 'send_resume_provide'
                ],
    'feedback_meeting_problem':
                [
                    'MakeChanges', 'RequestFeedback', 'PlanMeeting', 'OfferHelp'
                ],
    'feedback_meeting_problem_even':
                [
                    'MakeChanges', 'RequestFeedback', 'PlanMeeting', 'OfferHelp'
                ],
    'clustered':
                [
                    'extremeprogramming_egroups_xp_bxn_bhj_unsubscribe_yahoo_send_blank_docs',
       'oca_adapter_applframe_siebel_offline_sources_biogen_osa_development_sync',
       'so_my_lunch_you_she_me_love_baby_weekend_was',
       'jsp_jguru_faq_servlets_faqpage_interest_listserv_signoff_jspfaq_esperanto',
       'blackberry_handheld_sent_net_my_wireless_from_www_prakash_don',
       'expense_susan_simmons_alice_8022_finance_invoice_562_8000_invoices',
       'click_cards_greeting_remove_free_offers_99_credit_ebay_receive',
       'bugzilla_bug_bugs_fixed_show_bug_fix_blocker_howard_thanks_p5',
       '691737r3xvfuvde9_content_de697917r3v3xuve_disposition_base64_filename_encoding_transfer_attachment_type',
       'venk_amy_shukla_executive_8032_0797_763_noemi_blvd_8010',
       '6114_dbaca_8041_baca_394_dan_engineering_director_408_sales',
       'palm_pqa_emulator_handheld_vii_palmsource_os_application_store_darshan',
       'accenture_amit_ty_wang_we_our_with_robert_partner_avocadoit',
       'wireless_laura_8187_1103_355_avocadoit_8186_brett_henderson_ext',
       'toshi_japan_tokyo_nobuyuki_takaki_otani_5404_81_toshiya_japanese',
       'japanese_i18n_translation_localization_miyuki_characters_english_td_localized_strings',
       'channelwave_lead_leads_forecast_mitch_cw_pipeline_matt_partner_cj',
       'she_man_her_his_he_love_woman_desimasala_you_was',
       'meeting_avocadoit_408_562_fax_inc_jose_meet_2211_95131',
       'trish_lady_3756_505_8070_wireless_vp_ready_415_blvd',
       'alert_mobilesys_alerts_ricardo_delivery_dan_workflow_we_avocadoit_actionable',
       'cell_call_office_my_number_phone_me_home_urgent_reach',
       'everywhere_206_business_5105_6105_604_weller_323_scott_matt',
       'tests_test_testing_sanity_sharon_qa_cases_plan_functional_thanks',
       'thursday_30_fine_friday_tuesday_how_monday_3pm_wednesday_works',
       'srik_prasad_ravi_rajeev_om_thanks_divakar_ritesh_cheers_srikanth',
       'prakash_amitabh_meeting_lisa_he_thanks_him_rajeev_calendar_his',
       'margulies_debbie_8059_dbm_1052_393_408_562_manager_8100',
       'document_review_changes_thanks_feedback_documents_comments_please_me_list',
       'hp_dell_laptop_shipping_price_laptops_monitor_drive_nadir_pc',
       'ha_funny_lol_rofl_yes_oh_cool_yeah_too_ok',
       'era_rsilverton_8039_6789_845_enabling_silverton_ron_strategic_infrastructure',
       'screenprompt_step_input_loop_java_false_component_option_designer_awt',
       'sessions_statistics_emas_concurrent_memory_stress_load_test_time_servers',
       'training_chris_course_class_doug_week_donivan_schedule_we_day',
       'hp_fortunata_ux_robert_itrc_447_reps_packard_we_hewlett',
       '8039_6789_845_silverton_ron_strategic_everywhere_415_2211_95131',
       'epservlet_compiled_servlet_opt_deviceclientsession_code_httpservlet_ini_parser_aasaan',
       'msdirect_1999_received_marciak_smtp_invoked_dec_cpmta_0800_delivered',
       'siebel_accenture_ty_sales_pharmaceutical_we_demo_seebeyond_solution_crm',
       'pricing_hosting_fee_month_per_000_price_license_cost_fees',
       'intended_recipient_privileged_confidential_prohibited_notify_transmission_contain_immediately_sender',
       'neomar_rim_browser_goamerica_emulator_application_pager_darshan_goweb_go',
       'emds_emas_srik_bugs_bug_nora_testing_tasks_offline_thanks',
       'resume_mamta_interview_experience_he_resumes_position_bettadapur_candidate_birlasoft',
       'wirelessly_margulies_debbie_sent_avocadoit_1052_8059_393_inc_408',
       'slides_presentation_slide_powerpoint_presentations_deck_ppt_thanks_audience_attached',
       'microsoft_jp_linkid_2003_msdn_visual_net_ai2you_japan_bea',
       'india_sri_amma_yahoo_subha_her_appa_delhi_ur_lord',
       'iq_777_insiteful_promotions_kadanoff_marcia_begin_mkadanoff_officer_chief',
       'password_login_username_passwords_nadir_reset_passwd_user_account_thanks',
       'meeting_meetings_reschedule_schedule_calendar_scheduled_time_thanks_friday_monday',
       '8186_brett_welborn_1103_355_8524_800_account_ext_direct',
       'seat_lv_confirmed_equip_nonstop_ar_nbsp_coach_miles_jet',
       'wilhan_build_om_thanks_srik_branch_patch_sharon_ravi_builds',
       '8030_piyer_prakash_iyer_wirelessly_cto_founder_sr_vice_engineering',
       'fiercewireless_wireless_mobile_3g_market_its_nokia_______2002_carriers',
       'partner_sales_partners_we_meeting_helen_our_training_glenn_biz',
       'voice_voicegenie_voicexml_speech_demo_recognition_speechworks_speechgenie_tellme_applications',
       'zip_file_files_thanks_folder_jagrati_wilhan_me_hi_zipped',
       'sun_helen_shawn_iplanet_reps_robert_susane_we_rep_with',
       'etrade_trade_servers_problem_craig_ops_problems_bithi_we_arun',
       'ich_werner_hallo_du_die_und_das_ciao_nicht_ist',
       'demo_demos_we_elba_need_thanks_john_can_if_do',
       '8060_stewart______________________________cstewart_craig_telecom_7173_409_vice_california',
       'rfp_qwest_rfi_boeing_dan_response_questions_elba_rfps_mike',
       'mp3_music_fi_play_______lo_track_sync_click_cd',
       'problem_fix_resolved_issue_thanks_fixed_this_it_hi_let',
       'email_emails_mail_mails_nadir_mailbox_sent_thanks_problem_my',
       'webex_meeting_password_meetings_time_join_pacific_click_gmt_host',
       'oracle_hung_database_dbsetup_tablespace_10m_url_guid_8i_oracle8i_create',
       'laden_rm_rf_craig_taliban_bin_harper_usa_8175_hehe',
       'fax_faxstatus_faxed_faxes_sendfax_number_form_faxing_jfax_thanks',
       'jssebrowser_attribute_awt_browser_epo_java_component_defaulttreeselectionmodel_eventdispatchthread_container',
       'normal_sitraka_mimeole_priority_0400_msmail_4133_2400_v5_2416',
       'banamex_zenki_elba_demo_meshele_hp_linscott_dan_gustavo_mexico',
       'steve_john_elba_richard_thanks_stephen_fyi_om_romanowski_thank',
       'quinter_christopher_0736_3235_267_18940_newtown_trumbull_778_757',
       'solaris_cpu_usr_nt_cpus_mahesh_machine_concurrent_testing_grep',
       'vss_webbyphone_applicationsengineering_checked_updated_files_thanks_readme_folder_into',
       'mcafee_clinic_virus_ibuy_cid_campaign_norton_virusscan_infected_asp',
       'que_de_el_la_te_por_para_en_tu_un',
       'sitraka_truman_en_ritchie_keith_mozilla_0400_sm_mobility_dave',
       'spreadsheet_excel_sheet_thanks_updated_darshan_worksheet_xls_attached_application',
       'nadir_fernand_thanks_ok_fern_ll_care_great_om_let',
       'ruyben_thanks_sharyn_cj_fyi_me_let_will_know_lot',
       'crm_crmcommunity_customer_business_management_customers_research_patricia_seybold_psgroup',
       'vpn_hyperras_nadir_password_dupont_extranet_client_access_firewall_fernand',
       'xml_feed_dan_dtd_phani_meshele_6114_8041_we_dbaca',
       'rational_license_licenses_robot_software_863_floating_licensing_key_nora',
       'weblogic_bayview_nntp_bean_bea_mozilla_www4_posting_saxbuilder_1999',
       'java_aasaan_parser_screensession_bug_wbphtmlbrowser_awt_checked_interpreter_fix',
       'him_he_his_call_guy_talk_ll_left_me_number',
       'speechworks_grammar_telephony_antares_prompt_dialogic_ashish_recognition_tts_dna',
       'install_installer_wilhan_praveen_installation_sharon_thanks_yuyu_srik_installshield',
       'esmtp_0400_klg_id_po_received_aol_jess_menezes_sujan',
       'sprint_pcs_infoworld_scott_weller_sponsor_206_avocadoit_sprintpcs_with',
       'aes_ae_darshan_john_thanks_we_process_should_resource_this',
       'clearcase_wilhan_vob_vobserver_samba_problem_machine_bob_jagrati_view',
       'klg_klgroup_mozilla_jprobe_kl_1998_ed_esmtp_id_0400',
       'tournament_khoi_incyte_golf_luong_viet_loc_play_vuong_practice',
       'synchronizing_folder_item_offline_added_outbox_items_drafts_favorites_hierarchy',
       'ziffdavis_eletters1_bin10_newsscan_flo_brown_cgi_edu_listserv_magiccap',
       'fedex_tracking_order_shipped_ups_shipment_shipping_ship_newport_package',
       'allnetdevices_internet_http_sections_news_forums_newsletters_resources_newsletter_specs',
       'ip_255_bytes_63_ttl_external_128_reply_90ms_craig',
       'glenn_thanks_fyi_ok_pereira_om_below_comments_alex_this',
       'contract_kimberlie_agreement_contracts_signed_legal_review_trish_thanks_final',
       'palladium_germanium_titanium_cm_build_cpp_5ga_germanium_wilhan_fullinstaller_micros',
       'doug_7956_ep036_8744_instructor_field_palm_857_sr_408',
       'her_she_call_left_talk_called_me_yes_ll_back',
       'fares_hotwire_travelzoo_travel_trip_fare_rental_deals_rates_top20',
       'darshan_rishi_thanks_ll_chandu_john_let_know_fyi_great',
       'whaley_elisabeth_8189_prof_srvcs_assist_562_office_north_2211',
       'aml_pages_page_thanks_shailesh_hi_files_amlscript_file_werner',
       '781_6774_smialek_238_0330_9111_901_peter_229_regional',
       'nda_signed_sign_mutual_faxed_thanks_our_kimberlie_copy_fax',
       'payment_purchase_po_invoice_wait_method_requisition_budgeted_acct_quantity',
       'pdt_display_occurrence_hdml_error_pda_aml_x_completeflash_true_markable',
       'cards_card_7db08466_cardscan_business_avocadoit_mark_accucard_7dc88742_562',
       'mary_debbie_marie_susan_michelle_thanks_good_fyi_think_jm',
       'adkins_doug_7985_562_408_8100_schemena_5118_95131_ca',
       'salzmann_ontario_toronto_3593_arcy_darcysalzmann_infotriever_lotus_darcy_643',
       'salzmann_arcy_darcy_416_nor_darcysalzmann_infotriever_605_1076_260',
       'clickz_digitrends_printer_marketing_advertising_online_search_story_full_advertise',
       'craig_thanx_fyi_harper_ll_needfully_calvin_hartman_hehe_alot',
       'fidelity_paytrust_knox_phani_john_canada_7599_eur_account_ron',
       'ricardo_7984_4827_engineer_garcia_829_703_canuel_281_ray',
       'wml_32992900_wapforum_head_card_dtd_evoice_menuwoutalert_title_meta',
       'cmbuild3_cmadm_javamail_5773188_2553691_content_0scfuncsummary_7bit_filename_octet',
       'bug_562_bugs_408_95131_avocadoit_ca_200_jose_fixed',
       'tran_alex_8068_3877_420_408_cell_562_director_8100',
       '211_30122_gmbh_94098_mailwww_49_171_3845255_düsseldorf_germany',
       '8065_shirata_hirata_steven_operations_networks_562_8100_direct_408',
       'iq_mailhost_msdirect_donald_1999_session_4000008_133_menuwoutalert_hdml_0800',
       'tradeorderscn_tradestock_session_5000010_pda_msdirect_coffee_dec_0800_2448_nologon',
       'rayhan_abdulmughnee_7964_8122_206_engineer__________________________bin_systems_408',
       'hotel_jackie_flight_rooms_itinerary_ticket_figueroa_504_reservations_flights',
       'pocketpc_pocket_emulator_pc_device_nullnic_emulators_support_alexis_werner',
       'https_opt_epservlet_pass_servlet_round_million_______________________________________________statistics_funding',
       'richman_mike_forwards_0644_460_senior_415_cell_account_north',
       'logo_logos_eps_jaime_emma_toni_andersen_yes_ac_helen',
       'ace1234b_7772_pdf_publications_research_hotlines_9659_9765_2379_1391',
       'james_larrue_baulch_ntmachs10_sujan_utc_menezes_sitraka_date_reply',
       'wml_wapforum_card_dtd_head_ordered_wml_1_equiv_doctype_cache',
       'display_hdml_true_markable_ttl_ascii_rule_testetrade88456_error_auto',
       'ricardo_ray_thanks_dan_glenn_comments_thank_good_dave_him',
       '8096_khou_fang_recruiting_kfang_4796_technical_8107_manager_829',
       'whaley_elisabeth_assit_8189_8103_srvcs_vp_prof_everywhere_562',
       'yahoo_rfc822_hotmail_0700_received_apparently_mail_length_content_smtp',
       'ruth_jacinda_om_howard_thanks_ann_dean_ll_her_ascend',
       'laura_leaders_8187_henderson_70m_primed_inter_funded_including_digitalenterprises',
       'douga_doug_thanks_thank_john_you_here_cece_sorry_fyi',
       'jamcracker_fortune_sharyn_issue79_openair_herring100_mag_redherring_ruyben_named',
       'pqa_darshan_pqas_rishi_application_thanks_cashedge_baxish_please_me',
       'timesheet_timesheets_period_sheet_ending_darshan_please_baxish_thanks_nori',
       '02_46_48_deleted_cvs_53_alertsinstaller_file_aug_rrt',
       'wml_wapforum_card_dtd_newcontext_head_ordered_wml_1_true_equiv',
       'pda_ae_session_5000006_etrade_aml_screen_optionpreview_session_start_occurrence',
       'wml_wapforum_card_dtd_occurred_head_ordered_wml_1_equiv_doctype',
       'ejolt_services_service_src_ddtrading_templates_win_etradebank_pterm_cpp',
       '8105_tapling_8050_ceo_tel_president_mark_thnx_everywhere_562',
       'jaime_thanks_jamie_thank_website_andy_fyi_she_katrien_taku',
       'blackberry_stuart_finn_handheld_7950_9837_grantf_sent_frederiksen_753',
       'andy_thanks_wagoner_ll_jm_good_ok_this_think_you',
       'era_rsilverton_8039_6789_enabling_845_silverton_ron_boulevard_infrastructure',
       'synchronizing_folder_x_completeflash_afterstart_pda_ae_etrade_aml_error4_item',
       'stock_options_vesting_shares_option_board_susan_grant_exercise_grants',
       'umfax_sr_fax_inbound_containing_entry_received_pages_total_was',
       'venktesh_brief_shukla_blackberry_because_everywhere_sent_my_business_message',
       'onevent_clearvar_flycast_card_wml_onenterforward_502002_reconnect_wapforum_pdt',
       'pings14_5000021_testetradepdas14_attention_title_meta_body_head_historylisttext_palmcomputingplatform_temporarily',
       'attention_142006_title_meta_content_body_head_ascii_rule_historylisttext',
       'attachment_attachments_resend_sorry_forgot_attach_attachement_thanks_bobcat_here',
       'tie_tiecon_jayaram_simonil_venk_shukla_india_madhav_sridar_kailash',
       'idc_darshan_diva_thanks_divakar_shailesh_chandu_baxish_can_issues',
       'wml_true_error_pdt_wapforum_card_start_dtd_occurrence_102000',
       'xml_interest_xsl_archives_mailto_java_discussing_signoff_dom_listserv',
       'frameset_javascript_155744_stream020425_frames_qatests_frame_script_framesets_onload',
       'basex_attention_title_meta_body_head_historylisttext_palmcomputingplatform_occurrence_techwatch',
       '8080_chan_vp_david_development_business_562_thx_408_avocadoit',
       'hdml_session_4000008_menuwoutalert_ae_aml_occurrence_etrade_screen_pdt_error',
       'thank_thanks_sir_much_om_appreciate_very_buddy_bro_you',
       'stewart_mark_8042_facility_chairs_direct_manager_north_2211_95131',
       'change_volume_000_nasdaq_legend_portfolio_ameritrade_500_corp_low',
       'arun_thanks_om_srik_tony_douga_will_craig_dondi_dave',
       '8135_8107_martinez_germana_coordinator_human_st_resources_executive_everywhere',
       'pda_accountbalances_start_aml_attention_pdt_session_5000010_error_screen_occurrence',
       'icons_icon_splash_color_arun_bhagvan_bmp_gif_image_toolbar',
       'garcia_ricardo_7984_4827_829_engineer_cell_408_562_8100',
       'recipient_000c05a6_ims_mts_msexch_recognized_unknown_reach_original_following',
       'scoping_darshan_john_document_estimate_template_elba_analysis_thanks_completed',
       'wml_afterstart_wapforum_pdt_x_completeflash_card_dtd_pda_occurrence_ae',
       'wml_wapforum_card_dtd_newcontext_head_wml_1_equiv_doctype_cache',
       'conference_call_dial_pst_raindance_moderator_participant_number_00am_877',
       'menuwalertwtitle_hdml_session_4000001_ae_aml_etrade_menuwoutalert_screen_session_testetrade88456',
       'sounds_good_do_yeah_great_thanks_problem_ok_me_no',
       'attention_title_meta_content_body_head_122000_ascii_rule_historylisttext',
       'nil_session_5000005_stockpreview_pda_ae_showerrscn_tradeerr_aml_etrade_screen',
       '7977_gaskill_gal_dondi_gui_engineer_senior_software_562_9149',
       'head_title_meta_wml_loginaskuser_pdt_attention_occurrence_aml_epxml',
       'tony_thanks_om_below_srik_craig_comments_yes_see_la',
       '35874_89_munich_rené_romain_rromain_80807_4493066_leopoldstr_49',
       'ron_he_sas_thanks_him_ll_silverton_thought_look_this',
       'roopak_ravi_prasad_thats_look_om_thanks_cheers_please_will',
       'wrh_wrhambrecht_551_wr_hambrecht_intended_messages_orders_mail_8670',
       'canon_release2_elapsedtime_parser_features_txt_output_compare_test_alwayson',
       'pings6_5000021_testetradepdas6_attention_title_meta_body_head_historylisttext_palmcomputingplatform_occurrence',
       'shawn_sswanson_8067_5163_swanson_377_sun_suntone_california_blvd',
       'david_jeff_robert_chris_fyi_thanks_dave_george_discuss_peter',
       'pings30_4000020_display_hdml_true_markable_ttl_testetrade88456_occurrence_102000_60',
       'loginaskuser_logon_pdt_502001_connecting_palmcomputingplatform_busy_occurrence_testetradepda_error',
       'x_completeflash_afterstart_pda_ae_etrade_aml_screen_session_error4_session_5000004',
       'alaska_airlines_alaskaair_jon_air_kathi_kavitha_john_darshan_thanks',
       '5773188_cmbuild3_cmadm_javamail_octet_stream_filename_disposition_content_7bit',
       'meshele_jim_ko_thanks_mk_john_elba_me_call_please',
       'fyi_om_action_just_heads_honey_fyyi_ifyi_barney_posted',
       'training_chris_longstaffe_8132_7573_course_205_408__________________________562',
       'survey_surveys_radford_questionnaire_perseus_responses_complete_questions_glenn_we',
       'msexchangemta_msexch_recipient_delivered_0500_following_cdw_sent_re_rowe',
       'office_home_officedepot_monday_out_friday_am_come_working_returning',
       'bedroom_gardener_washer_rent_dryer_kitchen_house_bath_room_eileen',
       'ffe_india_facilitators_foundation_students_scholarship_suresh_committee_seshan_yahoo',
       'chen_diana_4689_8143______________________________________829_engineer_cell_everywhere_applications',
       'display_hdml_true_markable_ttl_testetrade88456_occurrence_60_102000_temporarily',
       '502001_connecting_palmcomputingplatform_busy_meta_head_testetradepda_pdt_start_error',
       'pda_session_5000005_movingmarkets_session_5000034_stockpreview_ae_102022_occurrence_etrade_aml',
       'visa_ins_murthy_immigration_petition_h1b_law_loewy_bernsen_sheela',
       'javaworld_jdj_sys_con_java_cfm_j2ee_jw_javaone_edition',
       'createflashscreen_x_createflash_phpclasses_upperdesign_session_5000011_pda_notification_dci_user_options_ae',
       'trade_kelsey_20001103_john_0mm_thanks_trading_fyi_steve_requalified',
       'thestandard_articles_1449_1999_newsletters_bdcimail_1151_standard_display_news',
       'cookies_persistent_cookie_storage_stored_device_feature_application_database_user',
       'synchronizing_folder_item_offline_rfp_gso_contacts_pocketmirror_17_updated',
       'getperformance_session_4000018_portfolio_hdml_emptydisableswitchacct_ae_etrade_aml_screen_session',
       'synchronizing_hierarchy_mailbox_folder_favorites_store_offline_patel_added_hdml',
       'cd_cds_burner_wilhan_nadir_om_burn_ashampoo_thanks_riaa',
       '408_8254_857_848_858_5769_206_sorry_650_thanks',
       'xsellsys_mehrak_sriram_darshan_application_chandu_scoping_thanks_url_rao',
       'attend_attending_invite_invitation_thanks_like_would_will_able_yes',
       'session_5000006_optionpreview_pda_tradeoptionerr_ae_aml_start_etrade_screen_occurrence',
       'onto_turn_exit_left_right_directions_miles_101_take_ramp',
       'jkouragian_kouragian_8012_jennifer_0060_588_boulevard_95054_3231_clara',
       'session_3000003_rim_stockpreview_ae_showerrscn_tradeerr_etrade_aml_screen_session',
       'zissen_lisa_8012_prakash_iyer_8104_2nd_founder_cto_assistant',
       '8006_tracy_0060_588_mark_phone_north_2211_95131_408',
       'ability_8186_anytime_customers_brett_anywhere_fact_non_interactive_access',
       'aasaan_designmodel_session_5000005_parser_import_sources_stockpreview_pda_getdesignmodelelement_dmdialog',
       'germana_german_thanks_ann_om_her_me_amy_she_you',
       'ep_intro_meeting_mtg_re_itf_toshiba_ntte_demo_dlj',
       '8016_barry_phillips_north_8100_562_2211_95131_director_direct',
       'unstrung_c001_smm_canada_apr_received_cp_zsm_po_menezes',
       'marcus_7978_9010_counsel_david_281_senior_650_corporate_8100',
       'release_features_glenn_rajeev_om_we_thanks_feature_howard_need',
       'rim_session_3000003_stockpreview_ae_etrade_aml_screen_session_testetraderim_occurrence',
       'sorry_here_oops_another_one_mistake_thinking_it_think_more',
       'wagoner_andrew_8174_purchasing_agent_direct_ca_2211_95131_200',
       'memory_application_crossed_limit_600_object_oct_session_5000009_pdt_142006_current',
       'jdbc_driver_connector_odbc_drivers_ms_oracle_sql_database_jsqlconnect',
       'freeyankee_optionpreview_offers_start_tradeoptionerr_aml_session_5000006_sending_session_3000004_202885',
       'hung_pokemon_steve_hang_pinball_abinov_paddle_craig_know_let',
       'recipient_prohibited_privileged_notify_designated_immediately_contain_sender_intended_confidential',
       'x_completeflash_afterstart_pda_ae_etrade_aml_screen_session_error4_function',
       'hdml_display_logon_true_markable_ttl_202002_testetrade88456_occurrence_60',
       'passed_tests_total_failed_aflowbenchmark_agentscalability_attention_title_meta_body',
       'title_meta_attention_body_head_historylisttext_palmcomputingplatform_occurrence_102000_testetradepda',
       'ipaq_compaq_siebel_qualified_win_richman_qualifies_limited_mobility_many',
       'aug_alerts_18_exec_21_22_edt_2001_15_00',
       'pings6_4000020_display_hdml_true_markable_ttl_testetrade88456_occurrence_102000_60',
       'richman_mike_forwards_0644_460_senior_415_cell_account_everywhere',
       'projector_projectors_infoworld_sausalito_room_mark_netsuite_portable_lcd_digital',
       'dave_thanks_om_cool_great_nice_wow_bible_vantra_did',
       'cerrone_kimberlie_9157_8069_5809_8109_7796148466_910_344_counsel',
       'ability_mobilize_anytime_anywhere_site_telephone_mobilizing_reach_fact_access',
       'research1_session_5000047_pda_showdatascn_techstockscom_ae_etrade_aml_screen_session',
       'attention_142006_content_meta_title_nsc_0700_body_head_webonphone',
       'nawabzada_8044_7289_205_administrator_nadir_cell_system_north_95131',
       'fx_8135_martinez_recruiting_germana_coordinator_ph_8107_hello_562',
       '2553691_offlineadmin_0scfuncsummary_cmbuild3_cmadm_javamail_content_filename_disposition_7bit',
       'sent_send_sending_sorry_it_yes_thanks_received_just_them',
       'outlook_exchange_mailbox_folders_mailboxes_backup_folder_click_mail_personal',
       'https_opt_epservlet_pass_servlet_statistics_etrade88456_etradepda_etraderim_smartphone',
       'ipaq_symbol_ppc_zone_beta_devzone_vivian_device_ppt8800_compaq',
       'attention_title_meta_content_body_head_ascii_rule_historylisttext_auto',
       'sep_502001_pdt_connecting_palmcomputingplatform_busy_meta_testetradepda_head_error',
       'session_4000008_menuwoutalert_hdml_ae_etrade_aml_menuwalertwtitle_screen_session_testetrade88456',
       'babycenter_1fc7nw_baby_le_ce_click_pregnancy_parents_parenting_dilemma',
       'unstrung_2002_2003_analysis_october_january_newsfeed_taken_bursts_december',
       'sybase_nasdaq_gideon_ianywhere_techwave_nyse_webtrends_portal_enterprise_george',
       'btopi_bt_weboe_btorder_num_htm_webmaster_approve_browse_ref',
       'acm_ibm_mjtracy_netcom_1999_org_ix_esmtp_id_efax',
       'aol_hotmail_mail_townsend_gwen_fw_com_msn_yahoo_net',
       'approved_approve_approval_thanks_jm_susan_accepted_lisa_blast_po',
       '243_773_mccann_60631_0324_0225_higgins_8745_district_360',
       'session_5000039_stocklistorder_pda_tradeoption_tradeorderscn_ae_etrade_aml_screen_session',
       'explorer_yahoo_msn______________________________________________________________________________________________________________________forwarded_download_mail_messenger_personal',
       'display_error_hdml_true_markable_ttl_failures_ascii_rule_auto',
       'pager_599_airmessage_ops_pagers_1661389_craig_408_operations_himmat',
       'visio_bhagavan_ajay_dds_darshan_utilitysrv1_document_open_version_misc',
       'session_3000003_rim_stockpreview_ae_tradeerr_showerrscn_etrade_aml_screen_session',
       'massage_massages_linda_sign_8135_martinez_room_germana_signup_8107',
       'weight_inferno2_pounds_diet_fat_health_mliang_lose_sending_loss',
       'error_errors_thanks_arun_problem_getting_attached_same_message_please',
       'blackberry_jm_handheld_sent_net_my_wireless_www_from_aft',
       'spec_functional_specs_review_ravi_om_func_ruth_thanks_features',
       'wml_research1_session_5000047_pda_wapforum_card_dtd_showalldatascn_wapservice_aml',
       'printer_paperport_staples_officedepot_exp_coupon_printers_savings_paper_expires',
       'sep_occurrence_pdt_onevent_clearvar_card_wrap_wml_occurrences_display',
       'display_true_hdml_markable_ttl_start_testetrade88456_pdt_error_err',
       'chg_ameritrade_750_500_250_625_875_vol_display_000',
       'newsletter_unplugged_newsletters_marilisa_out_list_mike_jaime_jm_week',
       'memory_application_crossed_limit_object_500_sep_current_high_value_type',
       'omnisky_spacer_tap_trish_steve_962_lady_latency_your_filter',
       'quarantined_vbs_loveletter_variant_infected_attachment_keqisoo_virus_attachments_reasons',
       'keys_key_lock_cabinets_kwick_drawers_cabinet_locksmith_locks_door',
       'memory_application_crossed_limit_sep_object_500_session_5000006_k_current_high_value',
       'dll_dlls_msvcp60_mfc42_msvcrt_8168_system32_version_install_machine',
       'session_4000003_menuwalertwtitle_hdml_ae_etrade_aml_menuwoutalert_screen_session_testetrade88456',
       '4309_270_8050_kadanoff_officer_marcia_chief_650_ready_mk',
       'krishna_ravi_prasad_thanks_checkin_look_into_yes_raam_om',
       'chg_ameritrade_vol_close_legend_375_500_125_low_symbol',
       'tran_pricing_alex_8068_3877_408_420_562_director_price',
       'internet_allnetdevices_devices_news_handhelds_search_boxes_resources_tell_2000',
       '2653_po_jun_klgroup_id_sujan_menezes_esmtp_0400_hqexch01',
       'cyberatlas_internet_article_big_picture_newsletter_http_online_1323_sections_html',
       'wilhan_shailesh_om_thanks_jagrati_yes_baxish_vacation_him_awake',
       'collateral_4cp_sheets_bleeds_sheet_emma_pieces_fold_hp_toni',
       'ert_ruth_jacinda_ecs_8006_mark_tracy_release_blvd_0060',
       'testetrade88456s14_pings14_4000020_display_hdml_true_markable_ttl_occurrence_60_102000',
       'pings10_4000020_testetrade88456s10_display_hdml_true_markable_ttl_occurrence_60_102000',
       '4368397_cmbuild3_cmadm_javamail_alwaysonocasummary_filename_disposition_content_7bit_attachment',
       'awong_8131_wong_562_andrew_5490_8102_819_dchan_408',
       'barry_mary_mk_thanks_sorry_fyi_phillips_jm_this_sent',
       'mehrak_jm_nother_thanks_elba_john_phani_scope_alexis_he',
       'memory_application_crossed_limit_object_500_current_high_value_type_pdt',
       'memory_application_crossed_600_limit_oct_object_attention_type_current_142006',
       'ameritrade_change_500_750_000_875_legend_375_625_250',
       '8054_2624_ricktor_245_assistant_blvd_650_mark_95054_3231',
       'pings30_5000021_head_meta_palmcomputingplatform_pdt_502001_start_connecting_true_occurrence',
       'logon_sep_502001_pdt_connecting_palmcomputingplatform_busy_testetradepda_occurrence_loginaskuser',
       '0000462763_frm_fon_msg_taken_zip_city_state_existing_refused',
       'works_worked_work_me_thanks_nadir_it_fine_try_tried',
       'display_hdml_pdt_true_markable_ttl_testetrade88456_wrap_occurrence_502001',
       'bayer_siebel_shozen_manabu_hideki_hh_issue_toshiba_shiva_takahiro',
       'gartner_www4_author_displaydocument_url_document_alert_title_id_displaycomparisoncolumn',
       'testetrade88456s12_pings12_4000020_display_hdml_true_markable_ttl_occurrence_102000_60',
       'emma_helen_advise_fyi_thanks_leahy_please_jon_know_great',
       'memory_application_crossed_600_limit_display_pdt_occurred_oct_hdml_object',
       'ftp_ws_ftp_ipswitch_fixup_isje_site_password_cuteftp_f5_pro',
       'belgium_usa_catalonia_sign_sweden_barcelona_mexico_espana_spain_signed',
       'session_3000007_rim_menuwoutalert_nologon_ae_etrade_aml_screen_session_testetraderim',
       'great_thanks_cool_perfect_awesome_excellent_thank_om_good_ok',
       'biogen_melissa_depalma_restrepo_joel_carlos_piyer_benghiat_melissa_sraghavan_iyer',
       'park_jennifer_8185_8102_strategy_emailed_thoughts_similar_speak_critical',
       'jivaroinc_jivaro_733_5156_5093_headhunters_vmware_cord_michael_recruiter',
       'loginaskuser_logon_pdt_502001_connecting_palmcomputingplatform_busy_occurrence_testetradepda_jun',
       'attention_title_logon_meta_body_head_historylisttext_login_palmcomputingplatform_occurrence',
       'palm_insync_active_session_count_handheld_store_crossed_online_limit_profile_hotsync',
       'failed_run_did_available_log_no_file_6ga_neon_cm_fullinstaller',
       'hdml_display_testetrade88456_occurrence_true_markable_ttl_err_start_pdt',
       'wml_wapforum_card_dtd_head_pdt_501003_occurrence_wml_1_equiv',
       'mitch_thanks_yer_toni_lets_care_me_this_jennifer_don',
       'dominoonlinesummary_4368397_onlinedomino_cmbuild3_cmadm_javamail_filename_disposition_content_7bit',
       '858_meltzer_3567_0033_547_southwest_774_david_dave_cell',
       'quicken_pqa_baxish_shailesh_darshan_chandu_application_production_chaitanya_thanks',
       'laporte_jon_9163_2040_985_98115_7041_309_wa_ne',
       'nike_stuart_tom_949_project_days_pilot_licensor_richard_prakash',
       'ich_sie_und_der_die_wir_ist_zu_den_das',
       'kimberlie_glenn_luck_her_she_fyi_thanks_comments_review_good',
       'docs_doc_thanks_tony_wilhan_attached_emma_dean_jacinda_here',
       'servers_server_nadir_restarted_thanks_michael_running_restart_steve_craig',
       'thinkmobile_addictive_x_completeflash_afterstart_pdt_meta_session_5000004_102022_friend_palmcomputingplatform',
       'java2d_image_listserv_body_bufferedimage_include_signoff_interest_java_int',
       'come_stop_here_ll_ok_see_am_way_over_there',
       'session_3000003_k_rim_stockpreview_ae_tradeerr_showerrscn_etrade_aml_sep_session',
       'amit_thanks_good_sounds_fyi_thx_great_looks_job_ty',
       'hdml_display_wrap_pdt_logon_502001_true_markable_ttl_connecting',
       '1519_petrone_noemi_8032_administrator_shukla_588_blvd_venk_executive',
       'blackberry_handheld_everywhere_sent_was_business_message_from_your_asterisk',
       'isgitt_512_6424_1275_636_514_scott_office_director_sales',
       'stanley_witter_morgan_dean_morganstanley_presentation_securities_limited_presentonline_cable',
       'badge_badges_david_visitor_mark_562_408_vasquez_lobby_yolanda',
       'devi_nora_thanks_lam_om_celeste_dan_w2_evening_ajay',
       'wml_wapforum_card_dtd_pings30_3000020_newcontext_head_ordered_wml_1_true',
       'pdt_502001_palmcomputingplatform_connecting_occurrence_testetradepda_busy_meta_error_start',
       'customerstartscreen_hdml_x_completeflash_error4_session_4000000_ae_etrade_aml_screen_session',
       'slides_slide_408_562_presentation_avocadoit_tran_420_alex_8100',
       'logoff_session_3000020_rim_ae_etrade_aml_screen_occurrence_afterstart_pdt',
       'airways_ticket_confirmed_fare_pittsburgh_2669082_tapling_pennsylvania_freq_aisle',
       'dds_darshan_customer_mehrak_screens_bhagavan_ui_document_rishi_mc',
       'pings12_4000020_testetrade88456s12_display_hdml_true_markable_ttl_102000_occurrence_60',
       'alwaysonosafuncsummary_4368397_cmbuild3_cmadm_javamail_osa_filename_disposition_content_7bit',
       'change_volume_nasdaq_legend_500_ameritrade_000_portfolio_symbol_low',
       'copy_copies_soft_hard_me_send_thanks_you_can_jm',
       'attention_pings10_5000021_title_meta_body_head_historylisttext_palmcomputingplatform_102000_occurrence',
       'miyuki_howard_om_thank_chad_her_tomorrow_thanks_sharon_nora',
       'session_5000006_optionpreview_pda_ae_etrade_tradeoptionerr_aml_screen_session_start',
       'car_honda_toyota_civic_ford_carsdirect_autoweb_bmw_volkswagen_jetta',
       'wml_menuwoutalert_wapforum_card_dtd_occurred_occurrence_head_ordered_wml_1',
       'nextaxiom_251_925_darren_linscott_1035_8400_unauthorized_addressee_8016_solely',
       'logs_log_logfile_file_6678_6677_thanks_roopak_logging_files',
       'wml_wapforum_card_dtd_head_wml_1_502001_equiv_doctype_cache',
       'dentist_appointment_dental_appt_tooth_teeth_canal_tomorrow_surgery_my',
       '5163_8067_sswanson_shawn_377_swanson_blvd_california_95054_3231',
       'cibc_otc_667_markets_world_affiliated_212_its_buy_company',
       'nda_mutual_sign_signed_fax_0852_749_connell_philip_director',
       'news_dailynews_msnbc_http_cnet_asp_nm_htm_1797847_1004',
       'link2buy_mliang_53488875_receiving_record_why_email_address_unsubscribe_jsp',
       'engr_mobilized_8041_6114_dbaca_394_baca_dan_director_avocadoit',
       'betty_pager_via_rim_sent_my_avocadoit_www_from_thx',
       'logoff_session_3000020_pdt_rim_occurrence_start_aml_502001_error_connecting',
       'customerstartscreen_hdml_x_completeflash_error4_ae_etrade_aml_screen_session_testetrade88456',
       'alice_susan_paiman_thanks_process_germana_please_cordinate_she_thx',
       'research1_session_5000047_pda_showdatascn_techstockscom_ae_etrade_aml_occurrence_screen',
       'session_5000005_stockpreview_pda_ae_etrade_aml_occurrence_showerrscn_tradeerr_screen',
       'hdml_wml_packet_wbmp_device_ravi_ie_emulator_tested_wmlsimulator',
       'brown_edu_magiccap_listserv_juno_canis_magic_received_148_2000',
       'ameritrade_portfolio_provided_quotes_index_onmoney_change_minutes_session_5000005_k_nasdaq',
       'interview_resume_marilisa_walski_newsletter_avocadoit_8144_position_interested_tantau',
       'sp8_sp10_sharon_fix_ravi_bugs_bug_fixes_sp7_glenn',
       'respond_jul_38_16_37_05_01_installer_jun_rrt',
       'wendy_brauner_5769_932_9223_1752_479_509_305_trade',
       'restrepo_carlos_8052_4083909518_9518_sprintpcs_engineer_390_sms_messaging',
       'session_5000006_optionpreview_pda_ae_etrade_aml_start_screen_session_occurrence',
       'kelsey_kelseys_thanks_thank_sacto_her_she_excellent_ll_fyi',
       'hdml_menuwalertwtitle_ae_etrade_aml_session_4000008_screen_session_4000003_session_testetrade88456',
       'sfba_rdc1_home_optionpreview_session_3000004_rim_0700_labinemedia_labine_ae',
       'howard_om_thanks_rajeev_yes_ravi_this_leaving_srik_jyoysana',
       'title_meta_occurrence_loginaskuser_attention_body_head_202002_pdt_historylisttext',
       'ie_ie5_problem_install_explorer_sp2_download_upgrade_patch_pdf',
       'tradehome_rim_session_3000003_ae_aml_start_etrade_testetraderim_screen_occurrence',
       'utilitysrv1_misc_automation_salesengineering_home_deleteme_folder_nadir_access_install',
       'emarketing_8144_8015_mcneely_jaime_891_cell_north_manager_jm',
       'stellcom_amit_robert_amr_bernie_larry_loring_questions_call_781',
       'domino_adapter_ravikumar_dominoadapter_sametime_jdbc_cases_ravi_testing_dominosession',
       'sweetums_vona_geoff_2650_0400_sitraka_sm_apr_id_dev_home',
       'look_looking_into_ll_take_check_checking_ok_now_am',
       'machine_machines_lab_nadir_michael_rajeev_thanks_ravi_know_use',
       '1_yes_3_devices_push_to_6_comments_extension2_1_do_you_use_a_wireless_device_3_to_2other_select_receive_newsletter_4_does_your_company_have_an_approved_budget_for_this_project',
       'exodus_uunet_himmat_craig_ip_pix_servers_346_linkshare_64'
                ]
}